import { useState } from 'react';

export type BodyPart = { id: string; name: string; description: string; x: number; y: number; width: number; height: number; color: string };

const partOptions = ['Head', 'Torso', 'Left arm', 'Right arm', 'Left leg', 'Right leg'];
const colors = ['#a78bfa', '#31c48d', '#f59e0b', '#60a5fa', '#f472b6', '#fb7185'];

export function BodyPartEditor({ source, width, height, parts, onChange }: { source: string; width: number; height: number; parts: BodyPart[]; onChange: (parts: BodyPart[]) => void }) {
  const [kind, setKind] = useState(partOptions[0]);
  const [description, setDescription] = useState('');
  const [start, setStart] = useState<{ x: number; y: number } | null>(null);
  const [draft, setDraft] = useState<BodyPart | null>(null);
  const point = (event: React.PointerEvent<HTMLDivElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { x: Math.max(0, Math.min(width, Math.round((event.clientX - rect.left) * width / rect.width))), y: Math.max(0, Math.min(height, Math.round((event.clientY - rect.top) * height / rect.height))) }; };
  const finish = (event: React.PointerEvent<HTMLDivElement>) => { if (!start) return; const end = point(event); const x = Math.min(start.x, end.x); const y = Math.min(start.y, end.y); const part: BodyPart = { id: `${kind}-${Date.now()}`, name: kind, description, x, y, width: Math.max(1, Math.abs(end.x - start.x)), height: Math.max(1, Math.abs(end.y - start.y)), color: colors[partOptions.indexOf(kind)] }; onChange([...parts.filter((item) => item.name !== kind), part]); setStart(null); setDraft(null); setDescription(''); };
  return <div className="body-parts-editor"><div><span className="label">STRUCTURE MAP</span><h3>Mark the body parts.</h3><p>Choose a part, then drag over its pixels. These regions describe the approved proportions and help pose generation keep the same character.</p></div><div className="body-part-controls"><select value={kind} onChange={(e) => setKind(e.target.value)}>{partOptions.map((item) => <option key={item}>{item}</option>)}</select><input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Describe this part, e.g. white swept hair and horns"/><span>Drag on sprite to mark</span></div><div className="body-part-canvas checker" onPointerDown={(e) => { e.currentTarget.setPointerCapture(e.pointerId); setStart(point(e)); }} onPointerMove={(e) => { if (start) { const end = point(e); setDraft({ id: 'draft', name: kind, description, x: Math.min(start.x, end.x), y: Math.min(start.y, end.y), width: Math.max(1, Math.abs(end.x - start.x)), height: Math.max(1, Math.abs(end.y - start.y)), color: colors[partOptions.indexOf(kind)] }); } }} onPointerUp={finish}><img src={source}/><svg viewBox={`0 0 ${width} ${height}`}><>{[...parts, ...(draft ? [draft] : [])].map((part) => <g key={part.id}><rect x={part.x} y={part.y} width={part.width} height={part.height} fill={part.color} fillOpacity=".2" stroke={part.color} strokeWidth={Math.max(1, width / 160)}/><text x={part.x + 1} y={part.y + 3} fill={part.color} fontSize={Math.max(2, width / 35)}>{part.name}</text></g>)}</></svg></div><div className="body-part-list">{parts.length === 0 && <span>No regions marked yet.</span>}{parts.map((part) => <div key={part.id}><i style={{ background: part.color }}/><strong>{part.name}</strong><small>{part.description || 'No description added'}</small><button onClick={() => onChange(parts.filter((item) => item.id !== part.id))}>Remove</button></div>)}</div></div>;
}
