import { composeRig, neutralTransform, type Segment, type SegmentTransform } from './segmentation';

export type RigJoint = { id: string; name: string; x: number; y: number; restX: number; restY: number; parentId?: string; minAngle?: number; maxAngle?: number };
export type RigBone = { id: string; name: string; parentJointId: string; childJointId: string; segmentId?: string; length: number; minAngle?: number; maxAngle?: number };
export type RigLayer = { id: string; segmentId: string; name: string; visiblePixels: number[]; completedSrc?: string; generatedPixels?: number[]; confidence: number; approved: boolean; pivot: { x: number; y: number }; zIndex: number };
export type PoseKeyframe = { id: string; cycleId: string; frameIndex: number; name: string; description: string; joints: Record<string, { x: number; y: number }>; transforms: Record<string, SegmentTransform>; preview: string; approved: boolean };
export type CharacterRig = { status: 'empty' | 'suggested' | 'approved'; joints: RigJoint[]; bones: RigBone[]; layers: RigLayer[]; poses: PoseKeyframe[] };
export type RigAnalysisSuggestion = { segments: Segment[]; joints: RigJoint[]; bones: RigBone[] };
export type CompletedRigLayer = { layerId: string; completedSrc?: string; generatedPixels: number[]; confidence: number };
export type PoseSuggestion = { joints: Record<string, { x: number; y: number }>; transforms: Record<string, SegmentTransform> };

export const emptyRig = (): CharacterRig => ({ status: 'empty', joints: [], bones: [], layers: [], poses: [] });
export const layersFromSegments = (segments: Segment[]): RigLayer[] => segments.map((segment) => ({ id: `layer-${segment.id}`, segmentId: segment.id, name: segment.name, visiblePixels: segment.pixels, generatedPixels: [], confidence: 1, approved: true, pivot: segment.pivot, zIndex: segment.zIndex }));
export const jointMap = (joints: RigJoint[]) => Object.fromEntries(joints.map((joint) => [joint.id, { x: joint.x, y: joint.y }]));

const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));
const distance = (a: { x: number; y: number }, b: { x: number; y: number }) => Math.hypot(a.x - b.x, a.y - b.y);
export function makeBone(id: string, name: string, parentJointId: string, childJointId: string, joints: RigJoint[], segmentId?: string): RigBone { const a = joints.find((joint) => joint.id === parentJointId)!; const b = joints.find((joint) => joint.id === childJointId)!; return { id, name, parentJointId, childJointId, segmentId, length: distance(a, b), minAngle: -170, maxAngle: 170 }; }

export function defaultSkeleton(width: number, height: number): { joints: RigJoint[]; bones: RigBone[] } {
  const point = (id: string, name: string, x: number, y: number, parentId?: string): RigJoint => ({ id, name, x: Math.round(width * x), y: Math.round(height * y), restX: Math.round(width * x), restY: Math.round(height * y), parentId });
  const joints = [point('root', 'Root', .5, .72), point('chest', 'Chest', .5, .48, 'root'), point('head', 'Head', .5, .25, 'chest'), point('shoulder-l', 'Left shoulder', .36, .46, 'chest'), point('elbow-l', 'Left elbow', .26, .60, 'shoulder-l'), point('hand-l', 'Left hand', .22, .72, 'elbow-l'), point('shoulder-r', 'Right shoulder', .64, .46, 'chest'), point('elbow-r', 'Right elbow', .74, .60, 'shoulder-r'), point('hand-r', 'Right hand', .78, .72, 'elbow-r'), point('hip-l', 'Left hip', .43, .70, 'root'), point('knee-l', 'Left knee', .41, .84, 'hip-l'), point('foot-l', 'Left foot', .39, .95, 'knee-l'), point('hip-r', 'Right hip', .57, .70, 'root'), point('knee-r', 'Right knee', .59, .84, 'hip-r'), point('foot-r', 'Right foot', .61, .95, 'knee-r')];
  const pairs: [string, string, string][] = [['spine','root','chest'],['neck','chest','head'],['upper-arm-l','shoulder-l','elbow-l'],['lower-arm-l','elbow-l','hand-l'],['upper-arm-r','shoulder-r','elbow-r'],['lower-arm-r','elbow-r','hand-r'],['upper-leg-l','hip-l','knee-l'],['lower-leg-l','knee-l','foot-l'],['upper-leg-r','hip-r','knee-r'],['lower-leg-r','knee-r','foot-r']];
  return { joints, bones: pairs.map(([id, parent, child]) => makeBone(id, id.replace(/-/g, ' '), parent, child, joints)) };
}

export async function analyzeSpriteLocally(source: string, width: number, height: number): Promise<RigAnalysisSuggestion> {
  const image = await new Promise<HTMLImageElement>((resolve, reject) => { const item = new Image(); item.onload = () => resolve(item); item.onerror = reject; item.src = source; });
  const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d')!; ctx.drawImage(image, 0, 0, width, height); const data = ctx.getImageData(0, 0, width, height).data;
  const skeleton = defaultSkeleton(width, height); const seeds = [{ id: 'head', name: 'Head', joint: 'head', color: '#a78bfa' }, { id: 'torso', name: 'Torso', joint: 'chest', color: '#31c48d' }, { id: 'arm-l', name: 'Left arm', joint: 'elbow-l', color: '#f59e0b' }, { id: 'arm-r', name: 'Right arm', joint: 'elbow-r', color: '#60a5fa' }, { id: 'leg-l', name: 'Left leg', joint: 'knee-l', color: '#f472b6' }, { id: 'leg-r', name: 'Right leg', joint: 'knee-r', color: '#22d3ee' }];
  const buckets = new Map(seeds.map((seed) => [seed.id, [] as number[]]));
  for (let pixel = 0; pixel < width * height; pixel += 1) { if (!data[pixel * 4 + 3]) continue; const x = pixel % width; const y = Math.floor(pixel / width); let best = seeds[0]; let bestScore = Infinity; for (const seed of seeds) { const anchor = skeleton.joints.find((joint) => joint.id === seed.joint)!; const spatial = Math.hypot((x - anchor.x) / width, (y - anchor.y) / height); const luminance = (data[pixel * 4] + data[pixel * 4 + 1] + data[pixel * 4 + 2]) / 765; const anchorBias = seed.id === 'head' ? Math.abs(luminance - .7) : Math.abs(luminance - .35); const score = spatial * 3 + anchorBias; if (score < bestScore) { best = seed; bestScore = score; } } buckets.get(best.id)!.push(pixel); }
  const segments = seeds.map((seed, index): Segment => { const anchor = skeleton.joints.find((joint) => joint.id === seed.joint)!; return { id: seed.id, name: seed.name, description: `Suggested ${seed.name.toLowerCase()} region`, color: seed.color, pixels: buckets.get(seed.id)!, pivot: { x: anchor.x, y: anchor.y }, zIndex: index, locked: false, visible: true }; });
  const bones = skeleton.bones.map((bone) => ({ ...bone, segmentId: segments.find((segment) => segment.name.toLowerCase().includes(bone.name.includes('arm') ? (bone.name.includes(' l') ? 'left arm' : 'right arm') : bone.name.includes('leg') ? (bone.name.includes(' l') ? 'left leg' : 'right leg') : bone.id === 'neck' ? 'head' : 'torso'))?.id }));
  return { segments, joints: skeleton.joints, bones };
}

export function solveTwoBoneIK(joints: RigJoint[], bones: RigBone[], endJointId: string, target: { x: number; y: number }): RigJoint[] {
  const end = joints.find((joint) => joint.id === endJointId); const mid = end && joints.find((joint) => joint.id === end.parentId); const root = mid && joints.find((joint) => joint.id === mid.parentId); if (!end || !mid || !root) return joints.map((joint) => joint.id === endJointId ? { ...joint, ...target } : joint);
  const upper = bones.find((bone) => bone.parentJointId === root.id && bone.childJointId === mid.id)?.length || distance(root, mid); const lower = bones.find((bone) => bone.parentJointId === mid.id && bone.childJointId === end.id)?.length || distance(mid, end); const dx = target.x - root.x; const dy = target.y - root.y; const reach = clamp(Math.hypot(dx, dy), Math.abs(upper - lower) + .001, upper + lower - .001); const base = Math.atan2(dy, dx); const shoulder = Math.acos(clamp((upper * upper + reach * reach - lower * lower) / (2 * upper * reach), -1, 1)); const bend = endJointId.includes('-l') ? -1 : 1; const angle = base + bend * shoulder; const nextMid = { x: Math.round(root.x + Math.cos(angle) * upper), y: Math.round(root.y + Math.sin(angle) * upper) };
  return joints.map((joint) => joint.id === mid.id ? { ...joint, ...nextMid } : joint.id === end.id ? { ...joint, x: Math.round(target.x), y: Math.round(target.y) } : joint);
}

export function transformsFromJoints(rest: RigJoint[], posed: RigJoint[], bones: RigBone[]): Record<string, SegmentTransform> { const transforms: Record<string, SegmentTransform> = {}; for (const bone of bones) { if (!bone.segmentId || transforms[bone.segmentId]) continue; const restA = rest.find((joint) => joint.id === bone.parentJointId); const restB = rest.find((joint) => joint.id === bone.childJointId); const poseA = posed.find((joint) => joint.id === bone.parentJointId); const poseB = posed.find((joint) => joint.id === bone.childJointId); if (!restA || !restB || !poseA || !poseB) continue; transforms[bone.segmentId] = { ...neutralTransform(), x: Math.round(poseA.x - restA.restX), y: Math.round(poseA.y - restA.restY), rotation: Math.round(((Math.atan2(poseB.y - poseA.y, poseB.x - poseA.x) - Math.atan2(restB.restY - restA.restY, restB.restX - restA.restX)) * 180) / Math.PI) }; } return transforms; }
export function interpolateTransforms(a: Record<string, SegmentTransform>, b: Record<string, SegmentTransform>, t: number): Record<string, SegmentTransform> { const ids = new Set([...Object.keys(a), ...Object.keys(b)]); return Object.fromEntries([...ids].map((id) => { const left = { ...neutralTransform(), ...(a[id] || {}) }; const right = { ...neutralTransform(), ...(b[id] || {}) }; return [id, { x: Math.round(left.x + (right.x - left.x) * t), y: Math.round(left.y + (right.y - left.y) * t), rotation: Math.round(left.rotation + (right.rotation - left.rotation) * t), visible: t < .5 ? left.visible : right.visible }]; })); }
export async function renderPose(source: string, width: number, height: number, segments: Segment[], transforms: Record<string, SegmentTransform>, layers: RigLayer[] = []): Promise<string> { const completed = Object.fromEntries(layers.filter((layer) => layer.approved && layer.completedSrc).map((layer) => [layer.segmentId, layer.completedSrc!])); return composeRig(source, width, height, segments, transforms, completed); }

const loadImage = (src: string) => new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = src; });
const hexRgb = (hex: string) => { const value = hex.replace('#', ''); return [Number.parseInt(value.slice(0, 2), 16), Number.parseInt(value.slice(2, 4), 16), Number.parseInt(value.slice(4, 6), 16)] as const; };
const rgbLab = (red: number, green: number, blue: number) => { const linear = [red, green, blue].map((value) => { const channel = value / 255; return channel > .04045 ? Math.pow((channel + .055) / 1.055, 2.4) : channel / 12.92; }); const x = (linear[0] * .4124 + linear[1] * .3576 + linear[2] * .1805) / .95047; const y = linear[0] * .2126 + linear[1] * .7152 + linear[2] * .0722; const z = (linear[0] * .0193 + linear[1] * .1192 + linear[2] * .9505) / 1.08883; const pivot = (value: number) => value > .008856 ? Math.cbrt(value) : 7.787 * value + 16 / 116; const fx = pivot(x); const fy = pivot(y); const fz = pivot(z); return [116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)] as const; };
export async function normalizeCompletedLayer(source: string, generated: string, width: number, height: number, palette: string[], visiblePixels: number[]): Promise<{ completedSrc: string; generatedPixels: number[] }> { const [sourceImage, generatedImage] = await Promise.all([loadImage(source), loadImage(generated)]); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d')!; ctx.imageSmoothingEnabled = false; ctx.drawImage(sourceImage, 0, 0, width, height); const sourceData = ctx.getImageData(0, 0, width, height); ctx.clearRect(0, 0, width, height); ctx.drawImage(generatedImage, 0, 0, width, height); const generatedData = ctx.getImageData(0, 0, width, height); const output = ctx.createImageData(width, height); const visible = new Set(visiblePixels); const colors = palette.map((hex) => ({ rgb: hexRgb(hex), lab: rgbLab(...hexRgb(hex)) })); const added: number[] = []; for (let pixel = 0; pixel < width * height; pixel += 1) { const offset = pixel * 4; if (visible.has(pixel)) { output.data.set(sourceData.data.slice(offset, offset + 4), offset); continue; } if (!generatedData.data[offset + 3]) continue; const lab = rgbLab(generatedData.data[offset], generatedData.data[offset + 1], generatedData.data[offset + 2]); const nearest = colors.reduce((best, color) => { const score = Math.hypot(lab[0] - color.lab[0], lab[1] - color.lab[1], lab[2] - color.lab[2]); return score < best.score ? { color, score } : best; }, { color: colors[0], score: Infinity }); if (!nearest.color) continue; output.data[offset] = nearest.color.rgb[0]; output.data[offset + 1] = nearest.color.rgb[1]; output.data[offset + 2] = nearest.color.rgb[2]; output.data[offset + 3] = 255; added.push(pixel); } ctx.putImageData(output, 0, 0); return { completedSrc: canvas.toDataURL('image/png'), generatedPixels: added }; }
