import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Check, Eraser, Eye, EyeOff, Hand, LoaderCircle, Paintbrush, Plus, RotateCcw, Sparkles, WandSparkles, ZoomIn, ZoomOut } from 'lucide-react';
import { assignPixels, defaultSegmentColors, neutralTransform, type Segment, type SegmentTransform } from './segmentation';
import { jointMap, layersFromSegments, normalizeCompletedLayer, renderPose, solveTwoBoneIK, transformsFromJoints, type CharacterRig, type PoseKeyframe, type RigJoint } from './rig';
import type { SpriteGenerationProvider } from './providers';

type Stage = 'analyze' | 'layers' | 'skeleton' | 'poses';
type Props = { source: string; width: number; height: number; palette: string[]; cycle: { id: string; name: string; frames: number; timing: number }; segments: Segment[]; rig: CharacterRig; provider: SpriteGenerationProvider; busy: boolean; onSegmentsChange: (segments: Segment[]) => void; onRigChange: (rig: CharacterRig) => void; onGenerateInbetweens: () => void; onContinue: () => void };

const stages: { id: Stage; label: string }[] = [{ id: 'analyze', label: '01 Analyze' }, { id: 'layers', label: '02 Layers' }, { id: 'skeleton', label: '03 Skeleton' }, { id: 'poses', label: '04 Poses' }];

function LayerPreview({ source, completedSrc, pixels, width, height }: { source: string; completedSrc?: string; pixels: number[]; width: number; height: number }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  useEffect(() => { if (completedSrc) return; const image = new Image(); image.onload = () => { const canvas = canvasRef.current; if (!canvas) return; canvas.width = width; canvas.height = height; const context = canvas.getContext('2d')!; context.imageSmoothingEnabled = false; context.drawImage(image, 0, 0, width, height); const sourceData = context.getImageData(0, 0, width, height); const output = context.createImageData(width, height); for (const pixel of pixels) { const offset = pixel * 4; output.data.set(sourceData.data.slice(offset, offset + 4), offset); } context.putImageData(output, 0, 0); }; image.src = source; }, [source, completedSrc, pixels, width, height]);
  return completedSrc ? <img src={completedSrc}/> : <canvas ref={canvasRef}/>;
}

export function RigView({ source, width, height, palette, cycle, segments, rig, provider, busy, onSegmentsChange, onRigChange, onGenerateInbetweens, onContinue }: Props) {
  const [stage, setStage] = useState<Stage>(rig.status === 'empty' ? 'analyze' : 'skeleton'); const [activeId, setActiveId] = useState(segments[0]?.id || ''); const [brushSize, setBrushSize] = useState(4); const [maskTool, setMaskTool] = useState<'paint' | 'erase' | 'pan'>('paint'); const [maskZoom, setMaskZoom] = useState(1); const [maskPan, setMaskPan] = useState({ x: 0, y: 0 }); const [alpha, setAlpha] = useState<Uint8ClampedArray | null>(null); const [poseDescription, setPoseDescription] = useState(''); const [poseName, setPoseName] = useState('Key pose'); const [poseIndex, setPoseIndex] = useState(0); const [posedJoints, setPosedJoints] = useState<RigJoint[]>(rig.joints); const [preview, setPreview] = useState(source); const [working, setWorking] = useState(''); const maskCanvas = useRef<HTMLCanvasElement>(null); const skeletonCanvas = useRef<HTMLCanvasElement>(null); const imageRef = useRef<HTMLImageElement | null>(null); const dragJoint = useRef<string | null>(null); const panStart = useRef<{ x: number; y: number; originX: number; originY: number } | null>(null);
  const activeSegment = segments.find((segment) => segment.id === activeId); const transforms = useMemo(() => transformsFromJoints(rig.joints, posedJoints, rig.bones), [rig.joints, rig.bones, posedJoints]);

  useEffect(() => { const image = new Image(); image.onload = () => { imageRef.current = image; const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d')!; ctx.drawImage(image, 0, 0, width, height); setAlpha(ctx.getImageData(0, 0, width, height).data); }; image.src = source; }, [source, width, height]);
  useEffect(() => { setPosedJoints(rig.joints); }, [rig.joints]);
  useEffect(() => { let cancelled = false; renderPose(source, width, height, segments, transforms, rig.layers).then((src) => { if (!cancelled) setPreview(src); }); return () => { cancelled = true; }; }, [source, width, height, segments, transforms, rig.layers]);
  useEffect(() => { const canvas = maskCanvas.current; const image = imageRef.current; if (!canvas || !image || !alpha) return; canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d')!; ctx.imageSmoothingEnabled = false; ctx.drawImage(image, 0, 0, width, height); for (const segment of segments) { ctx.fillStyle = `${segment.color}${segment.id === activeId ? 'aa' : '55'}`; for (const pixel of segment.pixels) ctx.fillRect(pixel % width, Math.floor(pixel / width), 1, 1); } }, [segments, activeId, alpha, width, height]);
  useEffect(() => { const canvas = skeletonCanvas.current; const image = imageRef.current; if (!canvas || !image) return; canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d')!; ctx.imageSmoothingEnabled = false; ctx.drawImage(image, 0, 0, width, height); ctx.lineWidth = Math.max(1, width / 100); for (const bone of rig.bones) { const a = posedJoints.find((joint) => joint.id === bone.parentJointId); const b = posedJoints.find((joint) => joint.id === bone.childJointId); if (!a || !b) continue; ctx.strokeStyle = '#c4b5fd'; ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke(); } for (const joint of posedJoints) { ctx.fillStyle = '#facc15'; ctx.beginPath(); ctx.arc(joint.x, joint.y, Math.max(2, width / 80), 0, Math.PI * 2); ctx.fill(); } }, [source, width, height, rig.bones, posedJoints]);

  const canvasPoint = (event: React.PointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { x: Math.round((event.clientX - rect.left) * width / rect.width), y: Math.round((event.clientY - rect.top) * height / rect.height) }; };
  const paintMask = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!alpha || !activeId || maskTool === 'pan') return; const point = canvasPoint(event); const min = -Math.floor((brushSize - 1) / 2); const max = Math.ceil((brushSize - 1) / 2); const pixels: number[] = []; for (let dy = min; dy <= max; dy++) for (let dx = min; dx <= max; dx++) { const x = point.x + dx; const y = point.y + dy; const pixel = y * width + x; if (x >= 0 && y >= 0 && x < width && y < height && alpha[pixel * 4 + 3]) pixels.push(pixel); } onSegmentsChange(assignPixels(segments, activeId, pixels, event.shiftKey || maskTool === 'erase' ? 'erase' : 'paint')); };
  const beginMaskInteraction = (event: React.PointerEvent<HTMLCanvasElement>) => { event.currentTarget.setPointerCapture(event.pointerId); if (maskTool === 'pan') { panStart.current = { x: event.clientX, y: event.clientY, originX: maskPan.x, originY: maskPan.y }; return; } paintMask(event); };
  const moveMaskInteraction = (event: React.PointerEvent<HTMLCanvasElement>) => { if (maskTool === 'pan' && panStart.current) { setMaskPan({ x: panStart.current.originX + event.clientX - panStart.current.x, y: panStart.current.originY + event.clientY - panStart.current.y }); return; } if (event.buttons) paintMask(event); };
  const endMaskInteraction = () => { panStart.current = null; };
  const changeMaskZoom = (amount: number) => setMaskZoom((current) => Math.max(.5, Math.min(5, Math.round((current + amount) * 4) / 4)));
  const resetMaskView = () => { setMaskZoom(1); setMaskPan({ x: 0, y: 0 }); };
  const analyze = async () => { setWorking('Analyzing anatomy…'); try { const result = await provider.analyzeRig({ source, width, height, palette, segments }); onSegmentsChange(result.segments); onRigChange({ status: 'suggested', joints: result.joints, bones: result.bones, layers: layersFromSegments(result.segments), poses: rig.poses }); setActiveId(result.segments[0]?.id || ''); } finally { setWorking(''); } };
  const approveAnalysis = () => { onRigChange({ ...rig, status: 'approved', layers: layersFromSegments(segments) }); setStage('layers'); };
  const completeLayers = async () => { setWorking('Completing hidden pixels…'); try { const completed = await provider.completeRigLayers({ source, width, height, palette, segments, layers: rig.layers }); const normalized = await Promise.all(rig.layers.map(async (layer) => { const result = completed.find((item) => item.layerId === layer.id); if (!result?.completedSrc) return result ? { ...layer, ...result, approved: false } : layer; const pixels = await normalizeCompletedLayer(source, result.completedSrc, width, height, palette, layer.visiblePixels); return { ...layer, ...result, ...pixels, approved: false }; })); onRigChange({ ...rig, layers: normalized }); } finally { setWorking(''); } };
  const setLayerApproved = (id: string, approved: boolean) => onRigChange({ ...rig, layers: rig.layers.map((layer) => layer.id === id ? { ...layer, approved } : layer) });
  const startJointDrag = (event: React.PointerEvent<HTMLCanvasElement>) => { const point = canvasPoint(event); const joint = posedJoints.reduce((nearest, item) => Math.hypot(item.x - point.x, item.y - point.y) < Math.hypot(nearest.x - point.x, nearest.y - point.y) ? item : nearest, posedJoints[0]); if (!joint) return; dragJoint.current = joint.id; event.currentTarget.setPointerCapture(event.pointerId); };
  const moveJoint = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!dragJoint.current) return; setPosedJoints((current) => solveTwoBoneIK(current, rig.bones, dragJoint.current!, canvasPoint(event))); };
  const endJointDrag = () => { dragJoint.current = null; };
  const suggestPose = async () => { if (!poseDescription.trim()) return; setWorking('Planning pose…'); try { const result = await provider.suggestPose({ source, width, height, palette, segments, description: poseDescription, joints: posedJoints, bones: rig.bones }); setPosedJoints((current) => current.map((joint) => ({ ...joint, ...(result.joints[joint.id] || {}) }))); } finally { setWorking(''); } };
  const savePose = async () => { const src = await renderPose(source, width, height, segments, transforms, rig.layers); const pose: PoseKeyframe = { id: `pose-${Date.now()}`, cycleId: cycle.id, frameIndex: Math.max(0, Math.min(cycle.frames - 1, poseIndex)), name: poseName.trim() || 'Key pose', description: poseDescription.trim(), joints: jointMap(posedJoints), transforms, preview: src, approved: true }; onRigChange({ ...rig, poses: [...rig.poses.filter((item) => !(item.cycleId === cycle.id && item.frameIndex === pose.frameIndex)), pose].sort((a, b) => a.frameIndex - b.frameIndex) }); };
  const loadPose = (pose: PoseKeyframe) => setPosedJoints(rig.joints.map((joint) => ({ ...joint, ...(pose.joints[joint.id] || {}) })));
  const addSegment = () => { const id = `segment-${Date.now()}`; onSegmentsChange([...segments, { id, name: `Section ${segments.length + 1}`, description: '', color: defaultSegmentColors[segments.length % defaultSegmentColors.length], pixels: [], pivot: { x: Math.floor(width / 2), y: Math.floor(height / 2) }, zIndex: segments.length, locked: false, visible: true }]); setActiveId(id); };

  return <section className="page rig-workspace"><div className="page-heading"><div><div className="eyebrow">OPTIONAL RIG · {cycle.name.toUpperCase()}</div><h2>Author the important poses.</h2><p>Build approved layers and key poses, then let the generator draw only the frames between them.</p></div><button className="ghost" onClick={onContinue}>Return to cycles</button></div><div className="rig-stage-tabs">{stages.map((item) => <button key={item.id} className={stage === item.id ? 'active' : ''} onClick={() => setStage(item.id)}>{item.label}{item.id === 'analyze' && rig.status === 'approved' ? <Check size={13}/> : null}</button>)}</div>{working && <div className="rig-working"><LoaderCircle className="spin" size={15}/>{working}</div>}
  {stage === 'analyze' && <div className="rig-stage-layout">
    <aside className="rig-side"><span className="label">REGIONS</span><button className="primary" disabled={Boolean(working)} onClick={analyze}><Sparkles size={15}/> Analyze sprite</button><button className="ghost" onClick={addSegment}><Plus size={14}/> Add custom region</button><div className="segment-list">{segments.map((segment) => <button key={segment.id} className={`segment-item ${activeId === segment.id ? 'active' : ''}`} onClick={() => setActiveId(segment.id)}><i style={{ background: segment.color }}/><span><strong>{segment.name}</strong><small>{segment.pixels.length} pixels</small></span></button>)}</div>{activeSegment && <><input value={activeSegment.name} onChange={(event) => onSegmentsChange(segments.map((segment) => segment.id === activeId ? { ...segment, name: event.target.value } : segment))}/><label className="brush-control">BRUSH <input type="range" min="1" max="25" value={brushSize} onChange={(event) => setBrushSize(Number(event.target.value))}/><output>{brushSize}px</output></label><small>{maskTool === 'erase' ? 'Drag to remove pixels from this region.' : maskTool === 'pan' ? 'Drag the canvas to reposition the view.' : 'Drag to assign pixels. Hold Shift to erase.'}</small></>}</aside>
    <div className="rig-main checker">
      <div className="mask-toolbar" role="toolbar" aria-label="Segmentation canvas tools"><div className="mask-tool-group"><button className={maskTool === 'paint' ? 'active' : ''} onClick={() => setMaskTool('paint')} title="Paint pixels into the selected region"><Paintbrush size={15}/><span>Paint</span></button><button className={maskTool === 'erase' ? 'active' : ''} onClick={() => setMaskTool('erase')} title="Erase pixels from the selected region"><Eraser size={15}/><span>Erase</span></button><button className={maskTool === 'pan' ? 'active' : ''} onClick={() => setMaskTool('pan')} title="Reposition the canvas"><Hand size={15}/><span>Move</span></button></div><div className="mask-tool-group zoom-tools"><button onClick={() => changeMaskZoom(-.25)} disabled={maskZoom <= .5} aria-label="Zoom out"><ZoomOut size={15}/></button><output>{Math.round(maskZoom * 100)}%</output><button onClick={() => changeMaskZoom(.25)} disabled={maskZoom >= 5} aria-label="Zoom in"><ZoomIn size={15}/></button><button onClick={resetMaskView} title="Reset zoom and position"><RotateCcw size={14}/><span>Reset</span></button></div></div>
      <div className="mask-canvas-viewport"><canvas ref={maskCanvas} className={`mask-canvas tool-${maskTool}`} style={{ transform: `translate(${maskPan.x}px, ${maskPan.y}px) scale(${maskZoom})` }} onPointerDown={beginMaskInteraction} onPointerMove={moveMaskInteraction} onPointerUp={endMaskInteraction} onPointerCancel={endMaskInteraction}/></div>
    </div>
    <aside className="rig-review"><span className="label">APPROVAL</span><h3>Confirm ownership</h3><p>Each opaque pixel can belong to one region. Correct the suggested masks before creating layers.</p><button className="primary" disabled={!segments.length} onClick={approveAnalysis}><Check size={15}/> Approve analysis</button></aside>
  </div>}
  {stage === 'layers' && <div className="layers-workspace"><div className="layers-intro"><div><span className="label">ANIMATION LAYERS</span><h3>Review each isolated body part.</h3><p>Every card shows only the pixels assigned on the previous step. Generate missing pixels only for areas hidden behind another part.</p></div><button className="ghost" disabled={Boolean(working) || !rig.layers.length} onClick={completeLayers}><WandSparkles size={15}/> Generate hidden areas</button></div><div className="layer-grid">{rig.layers.map((layer) => { const generatedCount = layer.generatedPixels?.length || 0; return <article className={`layer-card ${layer.approved ? 'approved' : ''}`} key={layer.id}><div className="layer-preview checker"><LayerPreview source={source} completedSrc={layer.completedSrc} pixels={layer.visiblePixels} width={width} height={height}/></div><div className="layer-card-copy"><strong>{layer.name}</strong><span>{layer.visiblePixels.length.toLocaleString()} visible pixels</span><small>{generatedCount ? `${generatedCount.toLocaleString()} hidden pixels generated` : 'Isolated from the approved segmentation'}</small></div><button className="ghost" onClick={() => setLayerApproved(layer.id, !layer.approved)}>{layer.approved ? <><Check size={13}/> Ready</> : 'Approve completion'}</button></article>; })}</div><div className="layers-footer"><span>{rig.layers.filter((layer) => layer.approved).length} of {rig.layers.length} layers ready</span><button className="primary" disabled={!rig.layers.length || rig.layers.some((layer) => !layer.approved)} onClick={() => setStage('skeleton')}>Continue to skeleton</button></div></div>}
  {stage === 'skeleton' && <div className="skeleton-workspace"><div className="skeleton-stage checker"><canvas ref={skeletonCanvas} onPointerDown={startJointDrag} onPointerMove={moveJoint} onPointerUp={endJointDrag} onPointerCancel={endJointDrag}/></div><aside className="skeleton-inspector"><span className="label">SKELETON</span><h3>Drag a joint</h3><p>Hands and feet use two-bone IK. Layer transforms remain integer-positioned with nearest-neighbor rotation.</p><div className="joint-list">{posedJoints.map((joint) => <div key={joint.id}><strong>{joint.name}</strong><span>{joint.x}, {joint.y}</span></div>)}</div><button className="ghost" onClick={() => setPosedJoints(rig.joints)}><RotateCcw size={14}/> Reset pose</button><button className="primary" onClick={() => setStage('poses')}>Use this skeleton</button></aside><div className="skeleton-preview checker"><img src={preview}/><span>COMPOSED POSE</span></div></div>}
  {stage === 'poses' && <div className="poses-workspace"><div className="pose-author"><div className="pose-preview checker"><img src={preview}/></div><div className="pose-fields"><label>POSE NAME<input value={poseName} onChange={(event) => setPoseName(event.target.value)}/></label><label>FRAME POSITION<input type="number" min="0" max={Math.max(0, cycle.frames - 1)} value={poseIndex} onChange={(event) => setPoseIndex(Number(event.target.value))}/></label><label>POSE DESCRIPTION<textarea value={poseDescription} onChange={(event) => setPoseDescription(event.target.value)} placeholder="e.g. waving hello, right hand raised beside the head"/></label><div><button className="ghost" disabled={!poseDescription.trim() || Boolean(working)} onClick={suggestPose}><Sparkles size={14}/> Suggest pose</button><button className="primary" onClick={savePose}><Plus size={14}/> Save key pose</button></div></div></div><div className="pose-timeline"><div><span className="label">KEY POSES · {cycle.frames} FRAME TIMELINE</span><strong>{rig.poses.filter((pose) => pose.cycleId === cycle.id).length} authored</strong></div><div className="pose-track">{Array.from({ length: cycle.frames }, (_, index) => { const pose = rig.poses.find((item) => item.cycleId === cycle.id && item.frameIndex === index); return <button key={index} className={pose ? 'has-pose' : ''} onClick={() => { setPoseIndex(index); if (pose) loadPose(pose); }}><span>{String(index + 1).padStart(2, '0')}</span>{pose ? <img src={pose.preview}/> : <i/>}<small>{pose?.name || 'In-between'}</small></button>; })}</div><div className="pose-actions"><button className="primary" disabled={busy || rig.poses.filter((pose) => pose.cycleId === cycle.id).length < 2} onClick={onGenerateInbetweens}><WandSparkles size={15}/> Generate in-between frames</button><small>At least two approved key poses are required. Authored poses remain unchanged.</small></div></div></div>}
  </section>;
}

export function RigFrameControls({ segments, transforms, onChange }: { segments: Segment[]; transforms: Record<string, SegmentTransform>; onChange: (transforms: Record<string, SegmentTransform>) => void }) { const update = (id: string, patch: Partial<SegmentTransform>) => onChange({ ...transforms, [id]: { ...neutralTransform(), ...(transforms[id] || {}), ...patch } }); return <div className="frame-rig-controls"><div><span className="label">SEGMENT POSE</span><p>Adjust this frame without redrawing its pixels.</p></div>{segments.map((segment) => { const transform = { ...neutralTransform(), ...(transforms[segment.id] || {}) }; return <div className="frame-rig-row" key={segment.id}><i style={{ background: segment.color }}/><strong>{segment.name}</strong><input aria-label={`${segment.name} x`} type="number" value={transform.x} onChange={(event) => update(segment.id, { x: Number(event.target.value) })}/><input aria-label={`${segment.name} y`} type="number" value={transform.y} onChange={(event) => update(segment.id, { y: Number(event.target.value) })}/><input aria-label={`${segment.name} rotation`} type="number" value={transform.rotation} onChange={(event) => update(segment.id, { rotation: Number(event.target.value) })}/><button onClick={() => update(segment.id, { visible: !transform.visible })}>{transform.visible ? <Eye size={13}/> : <EyeOff size={13}/>}</button></div>; })}</div>; }
